#! /bin/bash
# With TAP
#sshfs -o reconnect,sshfs_sync,idmap=user,transform_symlinks \
#    10.93.48.2: $HOME/sshfs/vm-nettest

# With user
sshfs -o reconnect,sshfs_sync,idmap=user,transform_symlinks,port=3962 \
    localhost: $HOME/sshfs/vm-nettest

