#! /bin/bash

cd `dirname $0`
# With TAP
if ! ip link show br0; then
    echo "Setup the bridge first, please."
    exit
fi
qemu-system-x86_64 -m 1024 -enable-kvm \
    -net nic,macaddr="52:54:00:12:34:64" \
    -net bridge,br=br0 \
    -drive file=netbsd.img,media=disk,format=raw
#qemu-system-x86_64 -m 1024 -enable-kvm \
#    -net nic \
#    -net bridge,br=br0 \
#    -drive file=netbsd.iso,media=cdrom \
#    -drive file=netbsd.img,media=disk,format=raw \
#    -boot c

# With User
# forwards an sshd to localhost:3962
#qemu-system-x86_64 -m 1024 -enable-kvm \
#    -net nic \
#    -net user,hostname=netbsd-vm,hostfwd=tcp::3962-:22 \
#    -net dump,file=nwtraffic.pcap \
#    -drive file=netbsd.img,media=disk,format=raw

